trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.5.1'
    addToPath: true

- script: |
    pip install Appium-Python-Client
    python -m unittest test_runner.py
  displayName: 'Run tests'